version: '3.9'
services:
  postgres:
    container_name: container-pg
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ticket_booking
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  mongodb:
    container_name: mongodb
    image: mongo
#    environment:
#      MONGO_INITDB_ROOT_USER: root
#      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    restart: unless-stopped

volumes:
  postgres-data: